services:
  - type: web
    name: bridge-gad
    env: python
    plan: free
    pythonVersion: "3.12"
    buildCommand: |
      # Set Python 3.12 explicitly
      python3.12 -m venv venv
      . venv/bin/activate
      
      # Install system dependencies
      apt-get update && apt-get install -y \
        cmake \
        g++ \
        libarrow-dev \
        zlib1g-dev \
        libssl-dev \
        liblz4-dev \
        libzstd-dev \
        libbz2-dev
      
      # Upgrade pip and setuptools first
      python -m pip install --upgrade pip setuptools wheel
      
      # Install core dependencies first
      python -m pip install --upgrade \
        pygments==2.19.2 \
        markdown-it-py==3.0.0 \
        rich==14.0.0 \
        --no-cache-dir
      
      # Install pyarrow with prebuilt wheels
      python -m pip install pyarrow==15.0.2 --only-binary :all: --no-cache-dir
      
      # Install the rest of the requirements
      python -m pip install -r requirements.txt --no-cache-dir
      
      # Verify installation
      python -c "import pyarrow; print(f'PyArrow version: {pyarrow.__version__}')"
    startCommand: "python app.py"
